name: githubactions
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK15
        uses: actions/setup-java@v1
        with:
          java-version: 15
          
        - name: Build with Maeven
          run: mvn -B package --file pom.xml